# Permalinks
permalink:        pretty

# Setup
url:              alexdenton.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Alex Denton

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Software Developer from Orlando, FL

# The tags listed as entries in the sidebar
sidebar_tags:     []

# Fallback image and color if not overwritten for tag or post
image:            /public/img/mountains.jpg
color:            '#A85641'

author:
  name:           'Alex Denton'
  twitter:        dentonlabs
  github:         AlexDenton
  photo:          /public/img/profile.png

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Alex. I'm a Software Developer from Orlando, FL.
